# Generated by Django 6.0.6 on 2026-06-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DebtInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "homeowners_insurance_yearly",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Annual homeowners insurance premium for the home.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "real_estate_tax_yearly",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Annual real estate property tax amount.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "car_insurance_total_premium",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Single total insurance premium for all vehicles in the household.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "car_insurance_frequency",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("semiannual", "Bi-Yearly (Every 6 Months)"),
                            ("yearly", "Yearly"),
                        ],
                        default="monthly",
                        max_length=12,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "loan_type",
                    models.CharField(
                        choices=[
                            ("mortgage", "Mortgage / Real Estate"),
                            ("car", "Car Loan"),
                            ("student", "Student Loan"),
                            ("other", "Other / Personal Loan"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="e.g. 'Primary Residence', '2022 Toyota Highlander'",
                        max_length=200,
                    ),
                ),
                (
                    "property_estimated_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Current estimated market value (real estate only)",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "expected_home_value_growth_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Expected annual home value increase % (mortgage loans only).",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "is_primary_residence",
                    models.BooleanField(
                        default=False,
                        help_text="Check if this is your primary residence. Primary residence equity is excluded from investable asset totals (shown separately). Non-primary/investment properties are included in asset calculations.",
                    ),
                ),
                ("original_balance", models.DecimalField(decimal_places=2, max_digits=14)),
                ("current_balance", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "interest_rate_pct",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Annual interest rate %, e.g. 6.750",
                        max_digits=6,
                    ),
                ),
                ("origination_date", models.DateField()),
                ("maturity_date", models.DateField()),
                (
                    "monthly_payment",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total monthly payment (P+I, or P+I+escrow if applicable)",
                        max_digits=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_escrowed",
                    models.BooleanField(
                        default=False,
                        help_text="Check if monthly payment includes escrowed insurance + taxes (mortgage only)",
                    ),
                ),
                (
                    "homeowners_insurance_yearly",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Annual homeowners insurance premium (mortgage only). These costs continue after loan payoff.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "real_estate_tax_yearly",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Annual real estate property tax (mortgage only). These costs continue after loan payoff.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "car_insurance_yearly",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Annual car insurance premium (car loan only). This cost continues after loan payoff.",
                        max_digits=12,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["loan_type", "description"],
            },
        ),
    ]
