# Generated by Django 6.0.6 on 2026-06-18 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExclusionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "description_contains",
                    models.CharField(
                        help_text="Case-insensitive substring match against CSV DESCRIPTION",
                        max_length=200,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "All Sources"),
                            ("checking", "Checking"),
                            ("credit", "Credit Card"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "amount_direction",
                    models.CharField(
                        choices=[
                            ("either", "Either (positive or negative)"),
                            ("negative", "Negative only (expenses/outflows)"),
                            ("positive", "Positive only (credits/inflows)"),
                        ],
                        default="either",
                        help_text="Restrict rule to only positive or only negative amounts, or match either.",
                        max_length=8,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 'Mortgage', 'TV Entertainment', 'Phone Plan'",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#6c757d",
                        help_text="Bootstrap/Chart.js color for pie chart",
                        max_length=7,
                    ),
                ),
                (
                    "is_debt_service",
                    models.BooleanField(
                        default=False,
                        help_text="Mark true for categories like mortgage/car/student loan payments.",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ImportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                ("bank", models.CharField(max_length=30)),
                ("source", models.CharField(max_length=10)),
                ("imported_count", models.IntegerField(default=0)),
                ("skipped_count", models.IntegerField(default=0)),
                ("staged_count", models.IntegerField(default=0)),
                (
                    "skip_details_json",
                    models.TextField(
                        blank=True,
                        help_text="JSON array of {date, description, amount, reason} for each skipped row.",
                    ),
                ),
            ],
            options={
                "ordering": ["-imported_at"],
            },
        ),
        migrations.CreateModel(
            name="MerchantMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "raw_description",
                    models.CharField(
                        help_text="Exact string from CSV DESCRIPTION column",
                        max_length=500,
                        unique=True,
                    ),
                ),
                (
                    "friendly_name",
                    models.CharField(help_text="e.g. 'Home Gas Bill'", max_length=200),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="budget.expensecategory",
                    ),
                ),
            ],
            options={
                "ordering": ["raw_description"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField()),
                ("raw_description", models.CharField(max_length=500)),
                ("friendly_name", models.CharField(blank=True, max_length=200)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Negative = expense, Positive = income/credit",
                        max_digits=12,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("checking", "Checking"), ("credit", "Credit Card")], max_length=10
                    ),
                ),
                ("check_number", models.CharField(blank=True, max_length=20)),
                ("status", models.CharField(blank=True, max_length=20)),
                (
                    "import_hash",
                    models.CharField(
                        help_text="SHA256 of date+description+amount to prevent duplicate imports",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "is_excluded",
                    models.BooleanField(
                        default=False,
                        help_text="Exclude from budget math/charts (e.g., internal transfers).",
                    ),
                ),
                ("exclusion_note", models.CharField(blank=True, max_length=200)),
                (
                    "is_pending_duplicate",
                    models.BooleanField(
                        default=False,
                        help_text="Staged for review — same date/description/amount/source already exists.",
                    ),
                ),
                (
                    "duplicate_source_hash",
                    models.CharField(
                        blank=True,
                        help_text="import_hash of the original transaction this may duplicate.",
                        max_length=64,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="budget.expensecategory",
                    ),
                ),
            ],
        ),
    ]
