[pytest]
DJANGO_SETTINGS_MODULE = rpt.test_settings
python_files = tests.py test_*.py
python_classes = Test*
python_functions = test_*
addopts = --cov=ai_insights --cov=assets --cov=budget --cov=core --cov=debts --cov=income --cov=life --cov=people --cov=retirement --cov-report=term-missing --cov-fail-under=30 -q