# Generated by Django 6.0.6 on 2026-06-18 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LifeEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "dependent_age_at_event",
                    models.IntegerField(
                        blank=True,
                        help_text="Age of dependent when this event occurs (required for dependent events)",
                        null=True,
                    ),
                ),
                (
                    "event_year_override",
                    models.IntegerField(
                        blank=True,
                        help_text="Year this event occurs (required for vacation / household events)",
                        null=True,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("vehicle", "Vehicle Purchase"),
                            ("education", "Secondary Education"),
                            ("move_out", "Leaves Household"),
                            ("vacation", "Vacation / Travel"),
                            ("wedding", "Wedding"),
                            ("other", "Other Expense"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cost in today's dollars (per occurrence)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "is_annual",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, this expense repeats every year starting from event year (e.g. annual vacation budget)",
                    ),
                ),
                (
                    "dependent",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "dependent"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="life_events",
                        to="people.person",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        help_text="Household member this event is tied to (vacation events)",
                        limit_choices_to={"role__in": ["user", "spouse"]},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="household_events",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "ordering": ["event_year_override", "dependent__name", "dependent_age_at_event"],
            },
        ),
    ]
