# Generated by Django 6.0.6 on 2026-06-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "api_provider",
                    models.CharField(
                        choices=[("openrouter", "OpenRouter")],
                        default="openrouter",
                        help_text="AI API provider for the AI Insights module. OpenRouter is currently the only supported provider.",
                        max_length=30,
                    ),
                ),
                (
                    "openrouter_api_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Your OpenRouter API key (sk-or-...). Get one at openrouter.ai. Stored only in your local database.",
                        max_length=255,
                    ),
                ),
                (
                    "openrouter_default_model",
                    models.CharField(
                        blank=True,
                        default="openai/gpt-4o",
                        help_text="OpenRouter model identifier (e.g. openai/gpt-4o, anthropic/claude-3-5-sonnet). See openrouter.ai/models.",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "App Settings",
            },
        ),
    ]
