# Generated by Django 6.0.6 on 2026-06-18 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(help_text="e.g. 'Fidelity Brokerage'", max_length=200)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("brokerage", "Brokerage"),
                            ("ira", "Traditional IRA"),
                            ("401k", "401(k) Traditional"),
                            ("roth_ira", "Roth IRA"),
                            ("roth_401k", "Roth 401(k)"),
                            ("crypto", "Crypto"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("institution", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "ordering": ["account_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="Holding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "ticker",
                    models.CharField(help_text="Stock/ETF/crypto ticker symbol", max_length=20),
                ),
                (
                    "name",
                    models.CharField(blank=True, help_text="Human-readable name", max_length=200),
                ),
                ("shares", models.DecimalField(decimal_places=6, max_digits=20)),
                (
                    "avg_cost_basis",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Average cost per share across all purchases",
                        max_digits=12,
                    ),
                ),
                (
                    "last_price",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
                ),
                ("last_price_updated", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holdings",
                        to="assets.account",
                    ),
                ),
            ],
            options={
                "ordering": ["ticker"],
            },
        ),
        migrations.CreateModel(
            name="MonthlyContribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("monthly_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="e.g. '401k payroll deduction into FSKAX'",
                        max_length=200,
                    ),
                ),
                (
                    "holding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributions",
                        to="assets.holding",
                    ),
                ),
            ],
        ),
    ]
