# Generated by Django 6.0.6 on 2026-06-18 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("spouse", "Spouse"),
                            ("dependent", "Dependent"),
                        ],
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "birth_month",
                    models.IntegerField(
                        blank=True,
                        help_text="Birth month (1–12)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "birth_year",
                    models.IntegerField(blank=True, help_text="Birth year (e.g. 1985)", null=True),
                ),
                (
                    "life_expectancy_age",
                    models.IntegerField(
                        blank=True,
                        help_text="Expected age at end of life — used in retirement drawdown calculations (user/spouse only)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(130),
                        ],
                    ),
                ),
                (
                    "retirement_age",
                    models.IntegerField(
                        blank=True,
                        help_text="Planned retirement age (user/spouse only). Used to derive retirement year.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(40),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "driving_age",
                    models.IntegerField(
                        blank=True,
                        help_text="Age dependent is expected to start driving (for future vehicle expense planning)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(14),
                            django.core.validators.MaxValueValidator(25),
                        ],
                    ),
                ),
                (
                    "move_out_age",
                    models.IntegerField(
                        blank=True,
                        help_text="Age dependent is expected to leave the household (for future expense reduction planning)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(14),
                            django.core.validators.MaxValueValidator(40),
                        ],
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("role__in", ["user", "spouse"])),
                        fields=("role",),
                        name="unique_people_user_and_spouse_role",
                    )
                ],
            },
        ),
    ]
