# Generated by Django 6.0.6 on 2026-06-18 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RaiseSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "raise_type",
                    models.CharField(
                        choices=[
                            ("annual_pct", "Annual % Raise"),
                            ("one_time", "One-Time Raise in Year"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "annual_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Annual raise % (e.g. 3.00 for 3%)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "one_time_year",
                    models.IntegerField(
                        blank=True, help_text="Year the one-time raise occurs", null=True
                    ),
                ),
                (
                    "one_time_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="New salary amount in that year",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raise_schedules",
                        to="people.person",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SocialSecurity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "monthly_benefit_age_62",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated monthly benefit if claimed at age 62 (from ssa.gov)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "monthly_benefit_fra",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated monthly benefit at Full Retirement Age — typically 67 (from ssa.gov)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "monthly_benefit_age_70",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated monthly benefit if claimed at age 70 (from ssa.gov)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "planned_claim_age",
                    models.IntegerField(
                        choices=[
                            (62, "Age 62 (Early — reduced benefit)"),
                            (63, "Age 63"),
                            (64, "Age 64"),
                            (65, "Age 65"),
                            (66, "Age 66"),
                            (67, "Age 67 (Full Retirement Age for most)"),
                            (68, "Age 68"),
                            (69, "Age 69"),
                            (70, "Age 70 (Maximum — delayed benefit)"),
                        ],
                        default=67,
                        help_text="Age you plan to start collecting Social Security",
                    ),
                ),
                (
                    "person",
                    models.OneToOneField(
                        limit_choices_to={"role__in": ["user", "spouse"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_security",
                        to="people.person",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="W2Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("employer", models.CharField(max_length=200)),
                ("annual_salary", models.DecimalField(decimal_places=2, max_digits=12)),
                ("effective_date", models.DateField(help_text="Date this salary became effective")),
                ("is_current", models.BooleanField(default=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="w2_incomes",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_date"],
            },
        ),
        migrations.CreateModel(
            name="Bonus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "bonus_type",
                    models.CharField(
                        choices=[("flat", "Flat Amount"), ("pct", "Percentage of Salary")],
                        max_length=4,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Dollar amount if flat; percentage (e.g. 10.00 for 10%) if pct",
                        max_digits=12,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "w2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bonuses",
                        to="income.w2income",
                    ),
                ),
            ],
        ),
    ]
